jobs:
  - name: img-manifest
    type: manifest
    steps:
      - IN: docker-image
      - IN: docker-options


  - name: deploy-ecr-to-ecs
    type: deploy
    steps:
      - IN: img-manifest
        force: true
      - IN: test-ecs